language: shell
dist: focal
addons:
  apt:
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu devel main universe
    update: true
    packages:
      - autopkgtest
      - dpkg-dev
      - rpm
      - xz-utils
before_script:
  - sudo apt-get -y build-dep ./
  - mkdir -pv ~/rpmbuild/BUILD ~/rpmbuild/BUILDROOT ~/rpmbuild/RPMS ~/rpmbuild/SOURCES ~/rpmbuild/SPECS ~/rpmbuild/SRPMS

script:
  - prove -v t
  - make origtarxz
  - dpkg-buildpackage -uc -us
  - sudo apt-get install -y ../pxzgrep_*_all.deb
  - autopkgtest -B ./ --- null
  - make dist-rpm
  - rpmbuild -ba pxzgrep.spec
