language: shell
dist: focal
addons:
  apt:
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu groovy main
    update: true
    packages:
      - perl
      - debhelper
      - autopkgtest
      - ronn
      - libtest-command-simple-perl
      - libtest-file-contents-perl
      - dpkg-dev
      - xz-utils
script:
  - prove -v t/*.t
  - dpkg-buildpackage -uc -us -b
