language: shell
dist: focal
addons:
  apt:
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu groovy main
    update: true
    packages:
      - autopkgtest
      - dpkg-dev
      - xz-utils
before_script:
  - sudo apt-get -y build-dep ./
script:
  - prove -v t/*.t
  - dpkg-buildpackage -uc -us -b
