language: shell
dist: focal
# Implies "virt: lxd"
arch: arm64

addons:
  apt:
    sources:
      - sourceline: deb http://ports.ubuntu.com/ubuntu-ports devel main universe
    update: true
    packages:
      - autopkgtest
      - dpkg-dev
      - lintian
      - rpm
      - xz-utils
before_script:
  - apt-cache policy
  - apt-cache policy ronn debhelper
  - sudo apt-get -y build-dep ./
  - mkdir -pv ~/rpmbuild/BUILD ~/rpmbuild/BUILDROOT ~/rpmbuild/RPMS ~/rpmbuild/SOURCES ~/rpmbuild/SPECS ~/rpmbuild/SRPMS

script:
  - prove -v t
  - make origtarxz
  - dpkg-buildpackage -uc -us
  - lintian --fail-on error -E -L '>=pedantic' ../pxzgrep_*.changes
  - sudo apt-get install -y ../pxzgrep_*_all.deb
  - autopkgtest -B ./ --- null
  - make dist-rpm
  - rpmbuild -ba pxzgrep.spec
