#!/bin/sh

# Copyright 2020 Axel Beckert <axel@ethz.ch>, ETH Zurich IT Security Center
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

# Same commandline handling as in pxzgrep, but massively stripped down
# to just being able to differentiate between options and positional
# parameters.
options=""
while getopts :-: p; do
    if [ "$p" = "-" ]; then
	options="$options --$OPTARG"
    elif [ "$p" = "?" ]; then
	options="$options -$OPTARG"
    fi
done
shift `expr $OPTIND - 1`
pattern="$1"
shift
file="$1"
shift

if [ -n "$*" ]; then
    echo "$0 only supports two parameters: a search pattern and a single file name" 1>&2
    exit 1;
fi

xzgrep $options "$pattern" "$file" > ./$(basename "$file" .xz)
rc=$?
case $rc in
    0) exit 1   ;;
    1) exit 0   ;;
    2) exit 255 ;;
esac
